import logging
from telegram import Update
from telegram.ext import Updater, CommandHandler, MessageHandler,  CallbackContext
import time

def start() :...
def delete_join_message() :...
def periodic_post() :...
def main() :...

if __name__ == "__main__":
    main()
